import { Branch, Year, Material, MaterialType, ForumPost, StudyTask, Notification, HomeGridCard } from './types';

export const branches: Branch[] = [
  Branch.Computer,
  Branch.IT,
  Branch.Mechanical,
  Branch.Civil,
  Branch.Electrical,
  Branch.ENTC,
];

export const years: Year[] = [
  Year.First,
  Year.Second,
  Year.Third,
  Year.Fourth,
];

export const materialTypes: (MaterialType | 'All')[] = ['All', ...Object.values(MaterialType)];

export const homeGridCards: HomeGridCard[] = [
    { id: 'fe-2024', title: 'SPPU FE ENGG 2024 PATTERN', bgColor: 'bg-blue-500', view: 'materials' },
    { id: 'fe-2019', title: 'SPPU FE ENGG 2019 PATTERN', bgColor: 'bg-yellow-500', view: 'materials' },
    { id: 'se-comp', title: 'SPPU SE COMP & AI&DS IMP SOL', bgColor: 'bg-green-500', view: 'materials' },
    { id: 'se-entc', title: 'SPPU SE E&TC & ELEC ENGG IMP SOL', bgColor: 'bg-pink-500', view: 'materials' },
    { id: 'se-it', title: 'SPPU SE IT & OTHER', bgColor: 'bg-red-500', view: 'materials' },
    { id: 'se-mech', title: 'SPPU SE MECH & CIVIL ENGG', bgColor: 'bg-purple-500', view: 'materials' },
    { id: 'te', title: 'SPPU THIRD YEAR ENGG', bgColor: 'bg-cyan-500', view: 'materials' },
    { id: 'be', title: 'SPPU LAST YEAR ENGG', bgColor: 'bg-teal-500', view: 'materials' },
];

export const materials: Material[] = [
  {
    id: 1,
    branch: Branch.Computer,
    year: Year.First,
    subject: 'Engineering Mathematics I',
    title: 'Engineering Mathematics I',
    description: 'Complete notes for Engineering Mathematics I, covering matrices, calculus, and differential equations.',
    size: '2.3MB',
    downloads: 245,
    uploaded: '11/5/2024',
    type: MaterialType.Notes,
    fileName: 'Eng_Maths_I_Notes.pdf',
    isApproved: true,
    uploaderEmail: 'admin@sppu.com',
    tags: ['maths', 'unit-1', 'calculus'],
  },
  {
    id: 2,
    branch: Branch.Computer,
    year: Year.First,
    subject: 'Basic Electrical Engineering',
    title: 'Basic Electrical Engineering',
    description: 'Complete notes for Basic Electrical Engineering, focusing on circuits and theorems.',
    size: '3.1MB',
    downloads: 198,
    uploaded: '11/5/2024',
    type: MaterialType.Notes,
    fileName: 'BEE_Notes.docx',
    isApproved: true,
    uploaderEmail: 'admin@sppu.com',
    tags: ['bee', 'circuits'],
  },
  {
    id: 3,
    branch: Branch.Computer,
    year: Year.First,
    subject: 'Engineering Physics',
    title: 'Engineering Physics',
    description: 'Complete notes for Engineering Physics, including topics on quantum mechanics.',
    size: '2.8MB',
    downloads: 178,
    uploaded: '11/5/2024',
    type: MaterialType.Notes,
    fileName: 'Physics_Chapter_1.pptx',
    isApproved: false, // Example of unapproved
    uploaderEmail: 'student@sppu.com',
    tags: ['physics', 'quantum'],
  },
  {
    id: 4,
    branch: Branch.IT,
    year: Year.First,
    subject: 'Engineering Chemistry',
    title: 'Engineering Chemistry Notes',
    description: 'Detailed notes covering the entire syllabus for chemistry.',
    size: '4.5MB',
    downloads: 310,
    uploaded: '10/28/2024',
    type: MaterialType.Notes,
    fileName: 'Chemistry_Syllabus_Notes.pdf',
    isApproved: true,
    uploaderEmail: 'admin@sppu.com',
    tags: ['chemistry', 'polymers'],
  },
  {
    id: 5,
    branch: Branch.Computer,
    year: Year.Second,
    subject: 'Data Structures & Algorithms',
    title: 'DSA PYQs (2019-2023)',
    description: 'PYQs and important questions for DSA.',
    size: '1.8MB',
    downloads: 560,
    uploaded: '10/25/2024',
    type: MaterialType.PYQ,
    fileName: 'DSA_PYQs_2019-2023.txt',
    isApproved: true,
    uploaderEmail: 'student2@sppu.com'
  },
  {
    id: 6,
    branch: Branch.Mechanical,
    year: Year.Third,
    subject: 'Thermodynamics',
    title: 'Thermodynamics PYQs',
    description: 'Previous year question papers for Thermodynamics.',
    size: '5.2MB',
    downloads: 412,
    uploaded: '10/22/2024',
    type: MaterialType.PYQ,
    fileName: 'Thermo_PYQ_Collection.pdf',
    isApproved: true,
    uploaderEmail: 'student@sppu.com'
  },
  {
    id: 7,
    branch: Branch.Civil,
    year: Year.Fourth,
    subject: 'Project Management',
    title: 'Project Management Assignments',
    description: 'Collection of solved assignments.',
    size: '3.5MB',
    downloads: 150,
    uploaded: '10/20/2024',
    type: MaterialType.Assignment,
    fileName: 'Project_Management_Assignment_1.png',
    isApproved: true,
    uploaderEmail: 'admin@sppu.com'
  },
  {
    id: 8,
    branch: Branch.Electrical,
    year: Year.Second,
    subject: 'Analog Circuits',
    title: 'Analog Circuits In-Sem Model Paper',
    description: 'A model paper to practice for the in-semester exam.',
    size: '2.1MB',
    downloads: 289,
    uploaded: '10/19/2024',
    type: MaterialType.ModelPaper,
    fileName: 'Analog_Circuits_Model_Paper.jpg',
    isApproved: true,
    uploaderEmail: 'student3@sppu.com'
  },
  {
    id: 9,
    branch: Branch.Computer,
    year: Year.Second,
    subject: 'Data Structures & Algorithms',
    title: 'Big O Notation Explained',
    description: 'A quick summary of common time complexities like O(1), O(log n), O(n), O(n log n), and O(n^2) with examples for sorting algorithms.',
    size: 'N/A',
    downloads: 42,
    uploaded: '11/6/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student@sppu.com',
    tags: ['dsa', 'complexity', 'algorithms', 'big-o'],
  },
  {
    id: 10,
    branch: Branch.Computer,
    year: Year.Second,
    subject: 'Object Oriented Programming',
    title: 'Core OOP Concepts: Encapsulation & Abstraction',
    description: 'Key differences between encapsulation (data hiding with getters/setters) and abstraction (hiding implementation details via interfaces). Simple Java examples provided.',
    size: 'N/A',
    downloads: 55,
    uploaded: '11/6/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student@sppu.com',
    tags: ['oop', 'java', 'concepts', 'encapsulation'],
  },
  {
    id: 11,
    // FIX: Corrected Branch enum usage. 'Branch.First' is invalid. Changed to 'Branch.Computer' as first year subjects are common and other similar entries use 'Computer'.
    branch: Branch.Computer,
    year: Year.First,
    subject: 'Engineering Mathematics I',
    title: 'Types of Matrices',
    description: 'Quick reference for Symmetric, Skew-Symmetric, Hermitian, and Skew-Hermitian matrices along with their defining properties (e.g., A = A^T).',
    size: 'N/A',
    downloads: 89,
    uploaded: '11/5/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student@sppu.com',
    tags: ['maths', 'm1', 'matrices', 'linear-algebra'],
  },
  {
    id: 12,
    // FIX: Corrected Branch enum usage. 'Branch.First' is invalid. Changed to 'Branch.Computer' for consistency.
    branch: Branch.Computer,
    year: Year.First,
    subject: 'Basic Electrical Engineering',
    title: 'Kirchhoff\'s Laws (KCL & KVL)',
    description: 'Summary of Kirchhoff\'s Current Law (sum of currents entering a node is zero) and Voltage Law (sum of voltages in a closed loop is zero). Essential for circuit analysis.',
    size: 'N/A',
    downloads: 112,
    uploaded: '11/4/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student2@sppu.com',
    tags: ['bee', 'circuits', 'kcl', 'kvl'],
  },
  {
    id: 13,
    branch: Branch.Computer,
    year: Year.Second,
    subject: 'Database Management Systems',
    title: 'Normalization Forms (1NF, 2NF, 3NF)',
    description: 'A simple explanation of the first three normal forms used to reduce data redundancy and improve data integrity in relational databases.',
    size: 'N/A',
    downloads: 76,
    uploaded: '11/3/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student3@sppu.com',
    tags: ['dbms', 'normalization', '1nf', '2nf', '3nf'],
  },
  {
    id: 14,
    branch: Branch.IT,
    year: Year.Third,
    subject: 'Computer Networks',
    title: 'OSI Model Layers Mnemonic',
    description: 'An easy way to remember the 7 layers of the OSI model: "Please Do Not Throw Sausage Pizza Away" (Physical, Data Link, Network, Transport, Session, Presentation, Application).',
    size: 'N/A',
    downloads: 130,
    uploaded: '11/2/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student@sppu.com',
    tags: ['cn', 'osi-model', 'networking', 'layers'],
  },
  {
    id: 15,
    // FIX: Corrected Branch enum usage. 'Branch.First' is invalid. Changed to 'Branch.Computer' for consistency.
    branch: Branch.Computer,
    year: Year.First,
    subject: 'Engineering Physics',
    title: 'Interference vs. Diffraction',
    description: 'Summary of key differences: Interference is due to superposition of waves from coherent sources, while diffraction is the bending of waves around obstacles.',
    size: 'N/A',
    downloads: 61,
    uploaded: '11/1/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student2@sppu.com',
    tags: ['physics', 'optics', 'interference', 'diffraction'],
  },
  {
    id: 16,
    // FIX: Corrected Branch enum usage. 'Branch.First' is invalid. Changed to 'Branch.Computer' for consistency.
    branch: Branch.Computer,
    year: Year.First,
    subject: 'Programming and Problem Solving',
    title: 'Pointers in C',
    description: 'Basic definition of a pointer, how to declare it using `*`, and how to get a variable\'s memory address using `&`. A simple code snippet is included.',
    size: 'N/A',
    downloads: 95,
    uploaded: '10/31/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student@sppu.com',
    tags: ['pps', 'c-programming', 'pointers', 'memory'],
  },
  {
    id: 17,
    branch: Branch.Computer,
    year: Year.Second,
    subject: 'Digital Electronics',
    title: 'Logic Gates Truth Tables',
    description: 'A quick cheat sheet with truth tables for all basic logic gates: AND, OR, NOT, NAND, NOR, XOR, and XNOR.',
    size: 'N/A',
    downloads: 150,
    uploaded: '10/30/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student3@sppu.com',
    tags: ['de', 'logic-gates', 'digital', 'truth-table'],
  },
  {
    id: 18,
    branch: Branch.IT,
    year: Year.Third,
    subject: 'Software Engineering',
    title: 'SDLC Models Overview',
    description: 'Brief comparison of Waterfall, Spiral, and Agile models for the Software Development Life Cycle (SDLC), highlighting the key pros and cons of each approach.',
    size: 'N/A',
    downloads: 48,
    uploaded: '10/29/2024',
    type: MaterialType.Notes,
    isApproved: true,
    uploaderEmail: 'student2@sppu.com',
    tags: ['se', 'sdlc', 'agile', 'waterfall'],
  },
];

export const forumPosts: ForumPost[] = [
    {
        id: 1,
        author: { name: 'Rohan Sharma', avatar: 'https://api.dicebear.com/8.x/initials/svg?seed=Rohan' },
        title: 'Is DSA important for placements in non-IT branches?',
        content: 'I am from Mechanical branch. I was wondering how much DSA matters for core company placements. Should I spend a lot of time on it?',
        timestamp: '2 hours ago',
        replies: 5,
        isAnonymous: false,
    },
    {
        id: 2,
        author: { name: 'Anonymous', avatar: 'https://api.dicebear.com/8.x/adventurer/svg?seed=anonymous' },
        title: 'Best resources for M1?',
        content: 'Struggling a bit with Engineering Mathematics 1, especially calculus. Any good YouTube channels or book recommendations?',
        timestamp: '1 day ago',
        replies: 12,
        isAnonymous: true,
    }
];

export const studyTasks: StudyTask[] = [
    { id: 1, title: 'Complete Unit 1 of Physics', subject: 'Engineering Physics', dueDate: '2024-11-15', isCompleted: false },
    { id: 2, title: 'Solve 5 DSA problems on arrays', subject: 'Data Structures', dueDate: '2024-11-12', isCompleted: true },
    { id: 3, title: 'BEE Lab Assignment Submission', subject: 'Basic Electrical Engg.', dueDate: '2024-11-14', isCompleted: false },
];

export const notifications: Notification[] = [
    { id: 1, message: 'Admin approved your "Thermodynamics PYQs" upload.', timestamp: '1 hour ago', isRead: false },
    { id: 2, message: 'New notes for "Engineering Chemistry" have been uploaded.', timestamp: '3 hours ago', isRead: false },
    { id: 3, message: 'Your "BEE Lab Assignment" is due tomorrow.', timestamp: '1 day ago', isRead: true },
];
